// Source of truth for ABOG's Step 2 Certifying Exam case-list structure:
// the three tabs (Obstetrics, Gynecology, Office Practice) on
// https://www.abog.org/get-certified/specialty-certification/step-2-certifying-exam/case-list,
// transcribed directly from screenshots of that page. Each section carries
// its own minimum patient count and a cap of 2 patients per category that
// count toward that minimum (extra cases beyond the cap still get listed —
// ABOG requires every patient to be listed — they just don't add to the
// minimum). Used to seed `categories` and to drive dashboard progress math,
// so the numbers shown to the user always trace back to this file.

const SECTIONS = {
  Obstetrics: {
    minimum: 20,
    maxPerCategory: 2,
    guidelines: [
      'Enter a minimum of 20 patients into the listed categories, but all patients must be listed. This includes all admitted as well as all short-stay and outpatient surgical patients, even if not officially admitted to a hospital.',
      'In order to meet the minimum, a candidate cannot count more than two patients in any of the categories listed below.',
      'If a candidate cannot list 20 obstetric cases in the categories listed below, an 18-month case list and/or an appropriate number of cases from fellowship or senior residency case logs may be included. If prior fellowship or senior resident cases are used, only list 20 cases.',
      'Separately enter each patient with a complication or abnormality, as well as medical and surgical intervention during pregnancy, labor, delivery, and the puerperium. Include the gestational age at admission. Normal, uncomplicated obstetrical patients should not be listed.',
    ],
    exclusionNote: {
      heading: 'The term "normal obstetrical patient" for this listing implies that the:',
      items: [
        'pregnancy, labor, delivery, and the puerperium were uncomplicated; and labor began spontaneously between the 39th and completion of the 41st week of gestation; patients delivering before 39 weeks gestation should be listed in the Spontaneous pre-term birth category;',
        'membranes ruptured or were ruptured after labor began;',
        'presentation was vertex, position was occiput OA, LOA or ROA, and labor was less than 24 hours in duration;',
        'delivery was spontaneous with or without episiotomy, from an anterior position;',
        'the infant had a five-minute Apgar score of 6 or more and weighed between 2500 and 4500 grams and was healthy, and',
        'placental delivery was uncomplicated, and blood loss was ≤ 500 mL.',
        'The "nights in hospital" includes all prenatal and postnatal nights. The number of nights listed is the arithmetic difference between the admission and discharge date.',
        'If a candidate cares for a patient in the hospital, but does not deliver the patient, the information on the delivery and infant should not be listed. For example, a patient who has preterm labor without delivery would not have delivery or infant information listed.',
      ],
    },
    categories: [
      'Co-existent medical comorbidities in the preconception, antenatal and intra and postpartum management.',
      'Abnormal carrier screening, aneuploidy screening, diagnostic testing',
      'Anomalous fetus identified during second-trimester',
      'Antepartum fetal assessment',
      'Spontaneous pre-term birth (including preterm labor/delivery, cervical insufficiency, PPROM)',
      'Multifetal gestation',
      'Fetal growth abnormalities',
      'Postterm gestation',
      'Stillbirth',
      'Hypertensive disorders of pregnancy',
      'Diabetes mellitus (pregestational and gestational)',
      'Medical disorders unique to pregnancy (hyperemesis, cholestasis of pregnancy, acute fatty liver of pregnancy, peripartum cardiomyopathy, PUPPP/PEP, pemphigoid gestationis, isoimmunization)',
      'Antepartum infections (HIV, varicella, parvovirus, syphilis, TORCH, COVID-19, pyelonephritis, etc.)',
      'Non-obstetrical emergencies during pregnancy (acute abdomen, adnexal masses, renal stone, trauma)',
      'Operative vaginal deliveries',
      'Cesarean deliveries',
      'Obstetrical lacerations',
      'Neonatal resuscitation and circumcisions',
      'Induction or augmentation of labor and labor abnormalities (e.g., dystocia, PROM, cord problems, abnormal position or presentation)',
      'Postpartum hemorrhage and uterine inversion',
      'Placental abnormalities',
      'Acute maternal decompensation',
      'Fetal heart rate abnormalities',
      'Prior cesarean delivery',
      'Infection in labor (e.g., chorioamnionitis, Group B streptococcus, HSV, HIV, HBV, HCV)',
      'Complicated vaginal deliveries (includes twin, vaginal breech, shoulder dystocia and ECV, excluding operative deliveries)',
      'Peripartum hysterectomy',
      'Immediate postpartum contraception',
      'Basic ultrasound (list number for first, second, and third trimester)',
      'Postpartum complications (including readmissions, lactation, and breastfeeding complications)',
    ],
  },

  Gynecology: {
    minimum: 20,
    maxPerCategory: 2,
    guidelines: [
      'Enter a minimum of 20 patients into the listed categories, but all patients must be listed. This includes all admitted as well as all short-stay and outpatient surgical patients, even if not officially admitted to a hospital.',
      'In order to meet the minimum, a candidate cannot count more than two patients in any of the categories listed below.',
      'If a candidate cannot list 20 gynecological cases in the categories listed below, an 18-month case list and/or an appropriate number of cases from fellowship or senior residency case logs may be included. If prior fellowship or senior resident cases are used, only list 20 cases.',
      'Patients who had an outpatient procedure in a surgical center must be listed on the Gynecology case list, not the Office Practice case list.',
      'A preoperative diagnosis should appear for all major and minor surgical procedures. The size of ovarian cysts and neoplasms must be recorded. For non-surgical conditions, the admission diagnosis should be recorded. Non-surgical admissions will not have a surgical pathological diagnosis. The treatment recorded should include all surgical procedures, as well as primary non-surgical therapy. "Surgical diagnosis" is the final pathology diagnosis. For hysterectomy specimens, the uterine weight in grams must be recorded. In cases without tissue for histologic diagnosis, the final clinical diagnosis should be listed. If the preoperative and postoperative diagnoses are the same and there is no pathology, you do not need to relist the diagnosis.',
      '"Nights in hospital" is the arithmetic difference between the date of discharge and the date of admission. Specific dates of admission and discharge should not be provided. If a patient had an outpatient procedure and was not admitted, list the number of nights in hospital as "0."',
    ],
    categories: [
      'Routine postoperative care',
      'Intraoperative and postoperative urologic complications',
      'Intraoperative and postoperative wound complications',
      'Intraoperative and postoperative vascular injuries and hemorrhage',
      'Intraoperative and postoperative nerve injury',
      'Intraoperative and postoperative gastrointestinal complications',
      'Postoperative pulmonary complications',
      'Adnexal emergencies, including PID/TOA, adnexal torsion, ruptured ovarian cysts',
      'Vulvar emergencies, including Bartholin gland duct abscess, vulvar abscess, fasciitis, straddle injury, sexual assault',
      'Ectopic pregnancies',
      'Pregnancies of unknown location',
      'Acute uterine complications, including hemorrhage, prolapsing fibroid, degenerating fibroid hematometra',
      'Urologic emergencies, including stones, pyelonephritis, diverticulum infection, obstruction associated with procidentia',
      'Pelvic infections',
      'Operative hysteroscopy',
      'Minimally invasive hysterectomy',
      'Operative laparoscopy',
      'Excisional procedures for preinvasive cervical disease',
      'Excisional procedures for vulvar lesions',
      'Dilation and curettage (non-obstetric)',
      'Vulvar or vaginal procedures',
      'Diagnostic cystoscopy',
      'Exploratory laparotomy',
      'Abdominal hysterectomy',
      'Abdominal myomectomy',
      'Open adnexal procedures',
      'Diagnostic and operative cystoscopy and urethroscopy',
      'Surgical repair of urinary incontinence',
      'Vesicovaginal fistula repair',
      'Surgical repair of pelvic organ prolapse, including apical prolapse and colpocleisis',
      'Obstetrical D&E and D&C (miscarriage and abortion management)',
      'Procedural management of abnormal first trimester pregnancy (non-emergent ectopic pregnancies, miscarriage)',
    ],
  },

  'Office Practice': {
    minimum: 40,
    maxPerCategory: 2,
    guidelines: [
      'Enter a total of 40 patients into the listed categories.',
      'Do not list more than two patients in any one category.',
      'List each patient separately, and include diagnostic procedures, treatment, results, and number of office visits during the 12-month period.',
      'Patients seen in the emergency room or triage area of labor and delivery may be listed.',
      'Do not include a patient that appears in the Gynecology or Obstetrics case lists.',
      'Do not include any patients that had procedures performed in any location except the office. Specifically, patients who had an outpatient procedure in a surgical center must be listed on the Gynecology case list.',
      'Patients who had virtual visits or COVID-19 patients for whom they were primarily responsible for care if they fit into one of the categories in the following list.',
    ],
    categories: [
      'Preventive health screening, immunization, and counseling (including cancer, mental health, IPV, sexual health, and genetic screening)',
      'Wellness recommendations (exercise, stress management, nicotine cessation, diet, and nutrition)',
      'Reproductive counseling and management',
      'Contraceptive counseling and management',
      'Pediatric and adolescent patients',
      'LGBTQIA patients',
      'Intimate partner violence and sexual assault',
      'Patients affected by psychiatric disorders (including PMDD)',
      'Patients with disabilities',
      'Patients with immunocompromised health',
      'Breast disorders (including preventive strategies)',
      'Primary care problems (non-obstetric/gynecologic-related)',
      'Patients with bone loss (including preventive strategies)',
      'Infertility and recurrent pregnancy loss',
      'Menopausal syndrome',
      'Disorders of sexual development and puberty',
      'Preinvasive cervical, vaginal, vulvar, and endometrial disease (colposcopy, biopsy, LEEP, EIN, hyperplasia, VIN/VAIN)',
      'Adnexal masses',
      'UTI',
      'Conditions of chronic pelvic pain and endometriosis (non-operative management)',
      'Sexual dysfunction',
      'Disorders of androgen excess',
      'Hyperprolactinemia and galactorrhea',
      'Amenorrhea',
      'Abnormal uterine bleeding',
      'Dysmenorrhea',
      'Vaginal discharge',
      'Sexually transmitted infections',
      'Vulvar skin conditions (e.g., contact dermatitis, lichen simplex chronicus, lichen sclerosis, lichen planus, hidradenitis suppurativa)',
      'Leiomyoma (evaluation and nonsurgical management)',
      'Endometrial/cervical polyps',
      'Adenomyosis',
      'Urinary incontinence',
      'Fecal incontinence',
      'Pelvic organ prolapse',
      'Fistula',
      'Evaluation and initial management of reproductive tract cancers',
      'Abortion management (Septic, threatened, incomplete)',
      'Ultrasonography (abdominal and transvaginal)',
    ],
  },
};

module.exports = { SECTIONS };
